In [ ]:
!pip install transformer_embeddings

Collecting transformer_embeddings
  Downloading transformer_embeddings-4.0.14-py3-none-any.whl (12 kB)
Collecting torch<2.0.0,>=1.9.1 (from transformer_embeddings)
  Downloading torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.5/887.5 MB 1.5 MB/s eta 0:00:00
Requirement already satisfied: transformers<5.0.0,>=4.36.0 in /usr/local/lib/python3.10/dist-packages (from transformer_embeddings) (4.41.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch<2.0.0,>=1.9.1->transformer_embeddings) (4.11.0)
Collecting nvidia-cuda-runtime-cu11==11.7.99 (from torch<2.0.0,>=1.9.1->transformer_embeddings)
  Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 46.7 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu11==8.5.0.96 (from torch<2.0.0,>=1.9.1->transformer_embeddings)
  Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.6 MB/s eta 0:00:00
Collecting nvidia-cublas-cu11==11.10.3.66 (from torch<2.0.0,>=1.9.1->transformer_embeddings)
  Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 3.4 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu11==11.7.99 (from torch<2.0.0,>=1.9.1->transformer_embeddings)
  Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 55.3 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch<2.0.0,>=1.9.1->transformer_embeddings) (67.7.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch<2.0.0,>=1.9.1->transformer_embeddings) (0.43.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (3.14.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (0.23.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (2024.5.15)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (0.4.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.36.0->transformer_embeddings) (4.66.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers<5.0.0,>=4.36.0->transformer_embeddings) (2023.6.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers<5.0.0,>=4.36.0->transformer_embeddings) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers<5.0.0,>=4.36.0->transformer_embeddings) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers<5.0.0,>=4.36.0->transformer_embeddings) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers<5.0.0,>=4.36.0->transformer_embeddings) (2024.2.2)
Installing collected packages: nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cublas-cu11, nvidia-cudnn-cu11, torch, transformer_embeddings
  Attempting uninstall: torch
    Found existing installation: torch 2.3.0+cu121
    Uninstalling torch-2.3.0+cu121:
      Successfully uninstalled torch-2.3.0+cu121
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.3.0+cu121 requires torch==2.3.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.18.0 requires torch>=2.3.0, but you have torch 1.13.1 which is incompatible.
torchvision 0.18.0+cu121 requires torch==2.3.0, but you have torch 1.13.1 which is incompatible.
Successfully installed nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 torch-1.13.1 transformer_embeddings-4.0.14

In [ ]:
pip install spellchecker contractions empath readability syntok fasttext

Collecting spellchecker
  Downloading spellchecker-0.4.tar.gz (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 41.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Collecting empath
  Downloading empath-0.89.tar.gz (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 7.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting readability
  Downloading readability-0.3.1.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Collecting syntok
  Downloading syntok-1.4.4-py3-none-any.whl (24 kB)
Collecting fasttext
  Downloading fasttext-0.9.2.tar.gz (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.8/68.8 kB 8.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spellchecker) (67.7.2)
Collecting inexactsearch (from spellchecker)
  Downloading inexactsearch-1.0.2.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from empath) (2.31.0)
Requirement already satisfied: regex>2016 in /usr/local/lib/python3.10/dist-packages (from syntok) (2024.5.15)
Collecting pybind11>=2.2 (from fasttext)
  Using cached pybind11-2.12.0-py3-none-any.whl (234 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fasttext) (1.25.2)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.2-py3-none-any.whl (289 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 30.4 MB/s eta 0:00:00
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.7/110.7 kB 13.6 MB/s eta 0:00:00
Collecting soundex>=1.0 (from inexactsearch->spellchecker)
  Downloading soundex-1.1.3.tar.gz (9.1 kB)
  Preparing metadata (setup.py) ... done
Collecting silpa_common>=0.3 (from inexactsearch->spellchecker)
  Downloading silpa_common-0.3.tar.gz (9.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->empath) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->empath) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->empath) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->empath) (2024.2.2)
Building wheels for collected packages: spellchecker, empath, readability, fasttext, inexactsearch, silpa_common, soundex
  Building wheel for spellchecker (setup.py) ... done
  Created wheel for spellchecker: filename=spellchecker-0.4-py3-none-any.whl size=3966500 sha256=2388fdf34872901c77b0c41b903e1cea371b42a732bd9e39a32e71fd5c183b84
  Stored in directory: /root/.cache/pip/wheels/6c/90/c3/eac248d8755b2a7343487a2087b4b29ad98f388c3c8c69c286
  Building wheel for empath (setup.py) ... done
  Created wheel for empath: filename=empath-0.89-py3-none-any.whl size=57800 sha256=ec5cb6f7c7f87c5a55e8beec1a9405b0a59865ad76de0d14e6e127fa9780a92b
  Stored in directory: /root/.cache/pip/wheels/92/b3/83/9eb2c6199881e2385a59d99bd911363475060ebeb4bdb27242
  Building wheel for readability (setup.py) ... done
  Created wheel for readability: filename=readability-0.3.1-py3-none-any.whl size=35460 sha256=33db02e06d5554085211fb3be8ec2dd1616ecdb58ad263d401179f4feacda502
  Stored in directory: /root/.cache/pip/wheels/05/07/4d/2e3a0aaba1713619a403e1a3c56e88a6fc12d753872b98771c
  Building wheel for fasttext (setup.py) ... done
  Created wheel for fasttext: filename=fasttext-0.9.2-cp310-cp310-linux_x86_64.whl size=4227138 sha256=1de71000a091c942406c85dd961ddd44cbe5bdced91f0468d63e3796dfff9eee
  Stored in directory: /root/.cache/pip/wheels/a5/13/75/f811c84a8ab36eedbaef977a6a58a98990e8e0f1967f98f394
  Building wheel for inexactsearch (setup.py) ... done
  Created wheel for inexactsearch: filename=inexactsearch-1.0.2-py3-none-any.whl size=7123 sha256=b4be1cab843f0c260990b97216f2d628ba154766568021e99af4eaad3d62cb43
  Stored in directory: /root/.cache/pip/wheels/63/19/2c/5e9f447f2533d457a1167c3e553f235e232b8a639e3f5fafab
  Building wheel for silpa_common (setup.py) ... done
  Created wheel for silpa_common: filename=silpa_common-0.3-py3-none-any.whl size=8466 sha256=24e0c3c5c610f9e3cd2bfe4b3cc8929dd4b5eda7197005915975594e39b80e95
  Stored in directory: /root/.cache/pip/wheels/c0/72/43/0c779b79d708c78240beb3b0bb8f5ff3c2ab81c4e5271ea1aa
  Building wheel for soundex (setup.py) ... done
  Created wheel for soundex: filename=soundex-1.1.3-py3-none-any.whl size=8876 sha256=b5be029ab7e02af2d78ac5c45a37fccdfbcfcf07d459bdd2091df292d70afd40
  Stored in directory: /root/.cache/pip/wheels/a7/c7/c0/99e0278924f5664ab201bee9eee6e7a856caabf95a6fe008c5
Successfully built spellchecker empath readability fasttext inexactsearch silpa_common soundex
Installing collected packages: readability, syntok, silpa_common, pybind11, pyahocorasick, anyascii, textsearch, soundex, fasttext, empath, inexactsearch, contractions, spellchecker
Successfully installed anyascii-0.3.2 contractions-0.1.73 empath-0.89 fasttext-0.9.2 inexactsearch-1.0.2 pyahocorasick-2.1.0 pybind11-2.12.0 readability-0.3.1 silpa_common-0.3 soundex-1.1.3 spellchecker-0.4 syntok-1.4.4 textsearch-0.0.24

In [ ]:
!pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence_transformers-3.0.0-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.7/224.7 kB 5.7 MB/s eta 0:00:00
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.41.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.66.4)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.13.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.25.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.11.4)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.23.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (3.14.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2023.6.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (6.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2.31.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (4.11.0)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (11.7.99)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (11.7.99)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.11.0->sentence_transformers) (67.7.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.11.0->sentence_transformers) (0.43.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (2024.5.15)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (0.4.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (3.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2024.2.2)
Installing collected packages: sentence_transformers
Successfully installed sentence_transformers-3.0.0

In [ ]:
pip install pyspellchecker

Collecting pyspellchecker
  Downloading pyspellchecker-0.8.1-py3-none-any.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 16.1 MB/s eta 0:00:00
Installing collected packages: pyspellchecker
Successfully installed pyspellchecker-0.8.1

In [ ]:
import pandas as pd
import re
from spellchecker import SpellChecker
import contractions
from empath import Empath
import readability
import syntok.segmenter as segmenter
from sentence_transformers import SentenceTransformer
import fasttext.util
import numpy as np
from transformer_embeddings import TransformerEmbeddings, mean_pooling
from huggingface_hub import login

In [ ]:
data = pd.read_csv('/content/Reddit_depression_dataset.csv')

In [ ]:
data

                                                   text     label
0     He said he had not felt that way before, sugge...      mild
1     Hey there r/assistance, Not sure if this is th...   minimum
2     My mom then hit me with the newspaper and it s...   minimum
3     until i met my new boyfriend, he is amazing, h...      mild
4     October is Domestic Violence Awareness Month a...  moderate
...                                                 ...       ...
3548  i have horrible vivid nightmares every night. ...  moderate
3549  Also I can't think about both of them without ...  moderate
3550  Furthermore, I told him before we got really s...      mild
3551  Here's the link to my amazon wish list where t...   minimum
3552  How can I keep us protected? They have already...   minimum

[3553 rows x 2 columns]

In [ ]:
data.iloc[3549]['text']

"Also I can't think about both of them without getting angry and jealous again, but to talk to each of them is actually helping me a lot.   ---   **tl;dr**: Three Friends where one M was fallen in Love with F and F was fallen in Love with the other M, which isn't feeling anything for her as an Girlfriend. We could be the best template for an 2,5h long Teenager-Drama.  ---"

In [ ]:
data['text']

0       He said he had not felt that way before, sugge...
1       Hey there r/assistance, Not sure if this is th...
2       My mom then hit me with the newspaper and it s...
3       until i met my new boyfriend, he is amazing, h...
4       October is Domestic Violence Awareness Month a...
                              ...
3548    i have horrible vivid nightmares every night. ...
3549    Also I can't think about both of them without ...
3550    Furthermore, I told him before we got really s...
3551    Here's the link to my amazon wish list where t...
3552    How can I keep us protected? They have already...
Name: text, Length: 3553, dtype: object

In [ ]:
def tokenize(text):
    return '\n\n'.join(
     '\n'.join(' '.join(token.value for token in sentence)
        for sentence in paragraph)
     for paragraph in segmenter.analyze(text))

In [ ]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)

data['text'] = data['text'].apply(lambda x: remove_urls(x))
data['text'] = data['text'].apply(lambda x: remove_html(x))

chat_words_str = """
AFAIK=As Far As I Know
AFK=Away From Keyboard
ASAP=As Soon As Possible
ATK=At The Keyboard
ATM=At The Moment
A3=Anytime, Anywhere, Anyplace
BAK=Back At Keyboard
BBL=Be Back Later
BBS=Be Back Soon
BFN=Bye For Now
B4N=Bye For Now
BRB=Be Right Back
BRT=Be Right There
BTW=By The Way
B4=Before
B4N=Bye For Now
B.S.=bullshit
B.S.,=bullshit,
BS=bullshit
BFF=Best Friends Forever
CU=See You
CUL8R=See You Later
CYA=See You
FAQ=Frequently Asked Questions
FC=Fingers Crossed
FWIW=For What It's Worth
FYI=For Your Information
GAL=Get A Life
GG=Good Game
GN=Good Night
GMTA=Great Minds Think Alike
GR8=Great!
G9=Genius
IC=I See
ICQ=I Seek you (also a chat program)
ILU=ILU: I Love You
IMHO=In My Honest/Humble Opinion
IMO=In My Opinion
IOW=In Other Words
IRL=In Real Life
KISS=Keep It Simple, Stupid
LDR=Long Distance Relationship
LMAO=Laugh My A.. Off
LOL=Laughing Out Loud
LTNS=Long Time No See
L8R=Later
MTE=My Thoughts Exactly
M8=Mate
NRN=No Reply Necessary
OIC=Oh I See
PITA=Pain In The A..
PRT=Party
PRW=Parents Are Watching
ROFL=Rolling On The Floor Laughing
ROFLOL=Rolling On The Floor Laughing Out Loud
ROTFLMAO=Rolling On The Floor Laughing My A.. Off
SK8=Skate
STATS=Your sex and age
ASL=Age, Sex, Location
THX=Thank You
TTFN=Ta-Ta For Now!
TTYL=Talk To You Later
U=You
U2=You Too
U4E=Yours For Ever
WB=Welcome Back
WTF=What The F...
WTG=Way To Go!
WUF=Where Are You From?
W8=Wait...
7K=Sick:-D Laugher
"""

chat_words_map_dict = {}
chat_words_list = []
for line in chat_words_str.split("\n"):
    if line != "":
        cw = line.split("=")[0]
        cw_expanded = line.split("=")[1]
        chat_words_list.append(cw)
        chat_words_map_dict[cw] = cw_expanded
chat_words_list = set(chat_words_list)

def chat_words_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words_list:
            new_text.append(chat_words_map_dict[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

data['text'] = data['text'].apply(lambda x: chat_words_conversion(x))

# creating an empty list
def expand_contractions(text):
    expanded_words = []
    for word in text.split():
        # using contractions.fix to expand the shortened words
        expanded_words.append(contractions.fix(word))

    expanded_text = ' '.join(expanded_words)
    return expanded_text

data['text'] = data['text'].apply(lambda x: expand_contractions(x))

spell = SpellChecker()
def correct_spellings(text):
    corrected_text = []
    misspelled_words = spell.unknown(text.split())
    for word in text.split():
        if word in misspelled_words:
            corrected_word = spell.correction(word)
            if corrected_word != None:
                corrected_text.append(corrected_word)
            else:
                corrected_text.append(word)
        else:
            corrected_text.append(word)
    try:
        return " ".join(corrected_text)
    except:
        print(text)

data['text'] = data['text'].apply(lambda x: correct_spellings(x))

In [ ]:
data['text'].iloc[0]

"He said he had not felt that way before suggested I go rest and so ..TRIGGER AHEAD IF YOUI'RE A HYPOCONDRIAC LIKE ME: i decide to look up feelings of doom in hopes of maybe getting sucked into some rabbit hole of ludicrous conspiracy a stupid are you psychic test or new age bullshit something I could even laugh at down the road No, I ended up reading that this sense of doom can be indicative of various health ailments one of which I am prone to So on top of my doom to my gloom..I am now fun worried about my heart I do happen to have a physical in 48 hours"

In [ ]:
data

                                                   text     label
0     He said he had not felt that way before sugges...      mild
1     Hey there r/assistance, Not sure if this is th...   minimum
2     My mom then hit me with the newspaper and it s...   minimum
3     until i met my new boyfriend he is amazing he ...      mild
4     October is Domestic Violence Awareness Month a...  moderate
...                                                 ...       ...
3548  i have horrible vivid nightmares every night s...  moderate
3549  Also I cannot think about both of them without...  moderate
3550  Furthermore, I told him before we got really s...      mild
3551  Here is the link to my amazon wish list where ...   minimum
3552  How can I keep us protected They have already ...   minimum

[3553 rows x 2 columns]

In [ ]:
for index, row in data.iterrows():
    f = open('/content/txt/{}.txt'.format(index), 'w')
    f.write(row['text'])
    f.close()

In [ ]:
import shutil

shutil.make_archive('txt', 'zip', 'txt')

'/content/txt.zip'

In [ ]:
from google.colab import files

files.download('txt.zip')

In [ ]:
data['label'] = data['label'].map({'minimum': 0, 'mild': 1, 'moderate': 2, 'severe' : 3})

In [ ]:
data

                                                   text  label
0     He said he had not felt that way before sugges...      1
1     Hey there r/assistance, Not sure if this is th...      0
2     My mom then hit me with the newspaper and it s...      0
3     until i met my new boyfriend he is amazing he ...      1
4     October is Domestic Violence Awareness Month a...      2
...                                                 ...    ...
3548  i have horrible vivid nightmares every night s...      2
3549  Also I cannot think about both of them without...      2
3550  Furthermore, I told him before we got really s...      1
3551  Here is the link to my amazon wish list where ...      0
3552  How can I keep us protected They have already ...      0

[3553 rows x 2 columns]

In [ ]:
data_seance = pd.read_csv('/content/results.csv')

In [ ]:
data_seance['id'] = data_seance['filename'].apply(lambda x: x.split('.')[0])
data_seance = data_seance.set_index('id').drop('filename', axis=1)
data.index.name = 'id'
data_seance.index = data_seance.index.astype(int)

In [ ]:
data = data.join(data_seance, how='inner')

In [ ]:
data

,text,label,nwords,Admiration/Awe_GALC,Amusement_GALC,Anger_GALC,Anxiety_GALC,Beingtouched_GALC,Boredom_GALC,Compassion_GALC,...,virtue_adverbs_component,positive_nouns_component,respect_component,trust_verbs_component,failure_component,well_being_component,economy_component,certainty_component,positive_verbs_component,objects_component
id,,,,,,,,,,,,,,,,,,,,,
0,He said he had not felt that way before sugges...,1,113,0.0,0.017699,0.000000,0.008850,0.000000,0.0,0.0,...,0.444753,-0.635348,0.177684,0.214367,0.017053,0.308501,0.289359,0.218807,-0.872000,0.034399
1,"Hey there r/assistance, Not sure if this is th...",0,111,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.005730,0.863369,0.084032,0.171506,0.015429,0.000000,0.021383,0.114919,0.906135,0.180283
2,My mom then hit me with the newspaper and it s...,0,167,0.0,0.005988,0.000000,0.000000,0.017964,0.0,0.0,...,0.000000,0.000000,0.000000,0.066249,0.000000,0.074509,0.522192,0.115689,0.011461,0.156417
3,until i met my new boyfriend he is amazing he ...,1,283,0.0,0.000000,0.003534,0.000000,0.003534,0.0,0.0,...,0.173659,0.581206,0.196990,0.149123,0.023879,0.121663,0.345603,0.179596,0.310530,0.117580
4,October is Domestic Violence Awareness Month a...,2,90,0.0,0.000000,0.022222,0.000000,0.000000,0.0,0.0,...,0.368876,-0.000233,0.010058,0.339390,0.078603,0.295835,0.597996,0.155633,-0.277722,0.099162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,i have horrible vivid nightmares every night s...,2,56,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,-0.879357,0.000000,0.139173,0.087654,0.201198,0.011000,0.230732,-0.872000,0.122610
3549,Also I cannot think about both of them without...,2,72,0.0,0.000000,0.013889,0.000000,0.000000,0.0,0.0,...,0.000000,0.876639,0.000000,0.306850,0.000000,0.010389,0.000000,0.189851,-0.275653,0.008361
3550,"Furthermore, I told him before we got really s...",1,75,0.0,0.000000,0.000000,0.013333,0.000000,0.0,0.0,...,0.008480,-0.875213,0.000000,0.050262,0.112262,0.475667,0.000000,0.087613,-0.872000,0.257464
3551,Here is the link to my amazon wish list where ...,0,64,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.868047,0.029259,0.025339,0.059231,0.000000,0.000000,0.182578,0.909281,0.301514
3552,How can I keep us protected They have already ...,0,63,0.0,0.000000,0.000000,0.000000,0.015873,0.0,0.0,...,0.000000,0.000000,0.016961,0.258210,0.018000,0.206206,0.011216,0.059635,0.000000,0.167317

In [ ]:
lexicon = Empath()

def get_empath_features(post):
    return lexicon.analyze(post, normalize=True)

data['empath_features'] = data['text'].apply(get_empath_features)

data = pd.concat([data, pd.DataFrame(list(data.empath_features)).add_prefix('emp_')], axis=1)
del data['empath_features']

In [ ]:
data

,text,label,nwords,Admiration/Awe_GALC,Amusement_GALC,Anger_GALC,Anxiety_GALC,Beingtouched_GALC,Boredom_GALC,Compassion_GALC,...,emp_weapon,emp_children,emp_monster,emp_ocean,emp_giving,emp_contentment,emp_writing,emp_rural,emp_positive_emotion,emp_musical
0,He said he had not felt that way before sugges...,1,113,0.0,0.017699,0.000000,0.008850,0.000000,0.0,0.0,...,0.0,0.008850,0.0,0.0,0.000000,0.000000,0.008850,0.008850,0.000000,0.000000
1,"Hey there r/assistance, Not sure if this is th...",0,111,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.009009,0.000000,0.000000,0.000000,0.000000,0.000000
2,My mom then hit me with the newspaper and it s...,0,167,0.0,0.005988,0.000000,0.000000,0.017964,0.0,0.0,...,0.0,0.005988,0.0,0.0,0.000000,0.000000,0.005988,0.000000,0.029940,0.005988
3,until i met my new boyfriend he is amazing he ...,1,283,0.0,0.000000,0.003534,0.000000,0.003534,0.0,0.0,...,0.0,0.021201,0.0,0.0,0.000000,0.035336,0.000000,0.000000,0.017668,0.000000
4,October is Domestic Violence Awareness Month a...,2,90,0.0,0.000000,0.022222,0.000000,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.011111,0.011111,0.000000,0.000000,0.011111,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,i have horrible vivid nightmares every night s...,2,56,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3549,Also I cannot think about both of them without...,2,72,0.0,0.000000,0.013889,0.000000,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.013889,0.000000,0.000000,0.013889,0.000000
3550,"Furthermore, I told him before we got really s...",1,75,0.0,0.000000,0.000000,0.013333,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3551,Here is the link to my amazon wish list where ...,0,64,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.015625,0.0,0.0,0.015625,0.000000,0.015625,0.000000,0.031250,0.000000
3552,How can I keep us protected They have already ...,0,63,0.0,0.000000,0.000000,0.000000,0.015873,0.0,0.0,...,0.0,0.015873,0.0,0.0,0.015873,0.000000,0.000000,0.015873,0.031746,0.000000

In [ ]:
data.to_csv('/content/almostpreprocessed/data_preliwc.csv')

In [ ]:
data['tokenized'] = data['text'].apply(tokenize)
od = data.apply(lambda x: readability.getmeasures(x['tokenized'], lang='en', merge=True), axis=1)
od = od.apply(pd.Series).add_prefix('readability_')
data = pd.concat([data, od], axis=1).drop(['tokenized'], axis=1)

In [ ]:
data.columns

Index(['text', 'label', 'nwords', 'Admiration/Awe_GALC', 'Amusement_GALC',
       'Anger_GALC', 'Anxiety_GALC', 'Beingtouched_GALC', 'Boredom_GALC',
       'Compassion_GALC',
       ...
       'readability_complex_words_dc', 'readability_tobeverb',
       'readability_auxverb', 'readability_conjunction', 'readability_pronoun',
       'readability_preposition', 'readability_nominalization',
       'readability_interrogative', 'readability_article',
       'readability_subordination'],
      dtype='object', length=499)

Embeddings

In [ ]:
model = SentenceTransformer('all-mpnet-base-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
embeddings = model.encode(data.text, show_progress_bar=True)
data['transformer_embeddings'] = embeddings.tolist()

Batches:   0%|          | 0/112 [00:00<?, ?it/s]

In [ ]:
fasttext.util.download_model('en', if_exists='ignore')  # English

Downloading https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.bin.gz

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

ValueError: ../pretrained-models/cc.en.300.bin cannot be opened for loading!

In [ ]:
ft = fasttext.load_model('/content/cc.en.300.bin')

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [ ]:
# create a new column called embeddings and apply the function to the dataset
data['ft_embeddings'] = data['text'].apply(lambda x: ft.get_sentence_vector(x).tolist())

In [ ]:
data.to_csv('/content/preprocessedData.csv', index=False)

In [ ]:
data.columns

Index(['text', 'label', 'nwords', 'Admiration/Awe_GALC', 'Amusement_GALC',
       'Anger_GALC', 'Anxiety_GALC', 'Beingtouched_GALC', 'Boredom_GALC',
       'Compassion_GALC',
       ...
       'readability_auxverb', 'readability_conjunction', 'readability_pronoun',
       'readability_preposition', 'readability_nominalization',
       'readability_interrogative', 'readability_article',
       'readability_subordination', 'transformer_embeddings', 'ft_embeddings'],
      dtype='object', length=501)

In [ ]:
model = SentenceTransformer('all-distilroberta-v1')
embeddings = model.encode(data.text, show_progress_bar=True)
data['distil_roberta_embeddings'] = embeddings.tolist()

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.3k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/653 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/112 [00:00<?, ?it/s]

In [ ]:
data.to_csv('/content/preprocessedData.csv', index=False)

In [ ]:
data

,text,label,nwords,Admiration/Awe_GALC,Amusement_GALC,Anger_GALC,Anxiety_GALC,Beingtouched_GALC,Boredom_GALC,Compassion_GALC,...,readability_conjunction,readability_pronoun,readability_preposition,readability_nominalization,readability_interrogative,readability_article,readability_subordination,transformer_embeddings,ft_embeddings,distil_roberta_embeddings
0,He said he had not felt that way before sugges...,1,113,0.0,0.017699,0.000000,0.008850,0.000000,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,"[-0.0006743494886904955, -0.01285542268306017,...","[-0.007061576936393976, -0.013467751443386078,...","[-0.061126187443733215, 0.007638456299901009, ..."
1,"Hey there r/assistance, Not sure if this is th...",0,111,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[0.022605326026678085, 0.015060145407915115, -...","[-0.007316493894904852, 0.0044315471313893795,...","[0.003977155778557062, 0.0017879154765978456, ..."
2,My mom then hit me with the newspaper and it s...,0,167,0.0,0.005988,0.000000,0.000000,0.017964,0.0,0.0,...,0.0,1.0,0.0,3.0,0.0,0.0,0.0,"[0.07074099034070969, -0.003647521836683154, -...","[-0.00012301577953621745, 0.010379962623119354...","[-0.015357895754277706, 0.04006315767765045, -..."
3,until i met my new boyfriend he is amazing he ...,1,283,0.0,0.000000,0.003534,0.000000,0.003534,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,"[0.014903290197253227, 0.021377546712756157, 0...","[0.0045671225525438786, -0.009834645316004753,...","[-0.012589546851813793, 0.014668954536318779, ..."
4,October is Domestic Violence Awareness Month a...,2,90,0.0,0.000000,0.022222,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,"[0.03318581357598305, 0.07784625142812729, 0.0...","[-0.016323337331414223, -0.009591460227966309,...","[0.011043553240597248, -0.037799008190631866, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,i have horrible vivid nightmares every night s...,2,56,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,"[0.04299173131585121, -0.004474240355193615, -...","[-0.014431629329919815, -0.0011266920482739806...","[0.004387537017464638, -0.04855622723698616, 0..."
3549,Also I cannot think about both of them without...,2,72,0.0,0.000000,0.013889,0.000000,0.000000,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,"[0.03265056014060974, -0.013125469908118248, -...","[0.00039376740460284054, -0.014767365530133247...","[0.001753989141434431, -0.020550284534692764, ..."
3550,"Furthermore, I told him before we got really s...",1,75,0.0,0.000000,0.000000,0.013333,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.025660289451479912, -0.01998322829604149, -...","[-0.0038584074936807156, -0.015921691432595253...","[-0.04715738818049431, 0.06682712584733963, 0...."
3551,Here is the link to my amazon wish list where ...,0,64,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[0.01763133332133293, 0.01317767333239317, -0....","[-0.0008206831989809871, -0.00781549047678709,...","[-0.009727059863507748, 0.000536331266630441, ..."
3552,How can I keep us protected They have already ...,0,63,0.0,0.000000,0.000000,0.000000,0.015873,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"[-0.02944069914519787, -0.04343601316213608, 0...","[-0.0008518618997186422, 0.007246619556099176,...","[0.005829012952744961, 0.008796026930212975, 0..."